name: release

on:
  push:
    branches:
      - release/**

jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
      - uses: actions/setup-node@v1
          with:
            always-auth: true

      - name: Setup npm registry
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc

      - name: Install dependencies
        run: yarn install

      - name: Run test
        run: yarn test

      - name: Run build
        run: yarn build

      - name: Publish
        run: |
          branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')
          yarn publish --new-version ${branch}
